name: Changelog caution

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install git://github.com/keyiiiii/github-changes.git#no-output-file

      - name: Run Changelog
        id: change_log
        run: |
          CHANGE_LOG="`node ./node_modules/github-changes -o keyiiiii -r changelog-github-actions -a --only-pulls --use-commit-body --for-tag upcoming -z Asia/Tokyo -k ${{ secrets.GITHUB_TOKEN }}`"
          echo -e "$CHANGE_LOG"
          echo ::set-output name=changelog::"$CHANGE_LOG"

      - name: Checke output parameter value changelog
        run: |
          echo -e "${{ steps.change_log.outputs.changelog }}"

      - uses: actions/github-script@0.3.0
        if: success()
        id: contract
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const str = '${{ steps.change_log.outputs.changelog }}';
            const pr = str.match(/- \[#/g);
            if (pr && pr.length > 10) {
              echo ::set-output name=isCaution::true
            }

      - name: Checke output parameter value isCaution
        run: |
          echo -e "${{ steps.contract.outputs.isCaution }}"
