name: Changelog caution

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install git://github.com/keyiiiii/github-changes.git#no-output-file

      - name: Run Changelog
        id: change_log
        run: |
          CHANGE_LOG_MAC="`node ./node_modules/github-changes -o keyiiiii -r changelog-github-actions -a --only-pulls --use-commit-body --for-tag upcoming -z Asia/Tokyo -k ${{ secrets.GITHUB_TOKEN }}`"
          CHANGE_LOG=`echo "$CHANGE_LOG_MAC" | sed s/\n/\r\n/g`
          echo ::set-output name=changelog::"$CHANGE_LOG"
          echo ::set-output name=changelog_mac::$CHANGE_LOG_MAC
          PR_LENGTH=`echo -e "$CHANGE_LOG" | grep -c -E '\- \[#[0-9]+\]'`
          echo ::set-output name=prlength::"$PR_LENGTH"

      - name: Checke output parameter value
        run: |
          echo ${{ steps.change_log.outputs.prlength }}
          echo ${{ steps.change_log.outputs.changelog_mac }}


      - name: Slack Notification
        if: steps.change_log.outputs.prlength > 2
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: private
          SLACK_MESSAGE: |
            未リリース分の PR が ${{ steps.change_log.outputs.prlength }} 件溜まってるよ！そろそろリリースしよ？
            ${{ steps.change_log.outputs.changelog_mac }}
          SLACK_TITLE: '警告！'
          SLACK_USERNAME: Changelog bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
