name: Changelog

on:
  issues:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install git://github.com/keyiiiii/github-changes.git#no-output-file

      - name: Run Changelog
        id: change_log
        run: |
          CHANGE_LOG=`node ./node_modules/github-changes -o keyiiiii -r changelog-github-actions -a --only-pulls --use-commit-body --for-tag upcoming -z Asia/Tokyo -k ${{ secrets.GITHUB_TOKEN }}`
          echo ::set-output name=changelog::$CHANGE_LOG
          echo $CHANGE_LOG
      - name: Check output parameter value
        run: |
          echo ${{ steps.change_log.outputs.changelog }}

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ GITHUB_TOKEN }}
          body: |
            '```${{ steps.change_log.outputs.changelog }}```'
