name: Changelog

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install git://github.com/keyiiiii/github-changes.git#no-output-file

      - name: Run Changelog
        id: change_log
        run: |
          CHANGE_LOG="`node ./node_modules/github-changes -o keyiiiii -r changelog-github-actions -a --only-pulls --use-commit-body --for-tag upcoming -z Asia/Tokyo -k ${{ secrets.GITHUB_TOKEN }}`"
          echo -e "$CHANGE_LOG"
          echo ::set-output name=changelog::"$CHANGE_LOG"

      - name: Checke output parameter value
        run: |
          echo -e "${{ steps.change_log.outputs.changelog }}"

      - uses: actions/github-script@0.3.0
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.issue.title.toUpperCase() === 'CHANGELOG') {
              const str = '${{ steps.change_log.outputs.changelog }}';
              github.issues.createComment({...context.issue, body: str})
            }
